# Generated by Django 4.1.1 on 2022-11-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forwardingEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
