# Generated by Django 4.1.1 on 2022-10-08 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BearerToken',
            fields=[
                ('key', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_bearertoken', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'BearerToken',
                'verbose_name_plural': 'BearerTokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BearerTokenProxy',
            fields=[
            ],
            options={
                'verbose_name': 'bearertoken',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.bearertoken',),
        ),
    ]
