# Generated by Django 4.1.1 on 2022-10-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
