# Generated by Django 4.1.2 on 2022-10-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='one_time_code',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
