# Generated by Django 4.1.1 on 2022-10-12 02:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bearertoken_bearertokenproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
