# Generated by Django 4.1.1 on 2022-10-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bearertoken_bearertokenproxy'),
        ('users', '0002_userprofile_one_time_code'),
    ]

    operations = [
    ]
