# Generated by Django 4.1.1 on 2022-10-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20221011_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='one_time_code',
            field=models.TextField(default='anything'),
        ),
    ]
