# Generated by Django 4.1.1 on 2022-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_friend_user_id_friends_friend_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
