# Generated by Django 4.1.1 on 2022-10-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_telephone_number'),
        ('users', '0004_alter_userprofile_one_time_code'),
    ]

    operations = [
    ]
