# Generated by Django 4.1.1 on 2022-10-11 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_friends_confirmed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('main_user', 'friend_user')},
        ),
    ]
