# Generated by Django 4.1.1 on 2022-10-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_friends_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set(),
        ),
    ]
