# Generated by Django 4.1.1 on 2022-10-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_telephone_number'),
        ('users', '0008_friends_temp_email_alter_friends_friend_user'),
    ]

    operations = [
    ]
