# Generated by Django 4.1.1 on 2022-11-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('receipts', '0010_alter_receipts_merchant_alter_receipts_receipt_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.category')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='receipts.receipts')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.subcategory')),
            ],
        ),
    ]
