# Generated by Django 4.1.1 on 2022-11-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0009_merge_20221104_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.FloatField()),
                ('name', models.CharField(max_length=36)),
                ('price', models.FloatField()),
                ('important_dates', models.DateField(blank=True, null=True)),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.receipts')),
            ],
        ),
    ]
