# Generated by Django 4.1.1 on 2022-11-16 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_category_id',
        ),
    ]
