# Generated by Django 4.1.1 on 2022-11-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
