# Generated by Django 4.1.1 on 2022-11-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_alter_receipts_receipt_image'),
        ('item', '0002_alter_item_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receipt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.receipts'),
        ),
    ]
