# Generated by Django 4.1.1 on 2022-11-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receipt_id',
            field=models.IntegerField(),
        ),
    ]
