# Generated by Django 4.1.1 on 2022-11-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_receipt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='receipt_id',
            new_name='receipt',
        ),
    ]
