# Generated by Django 4.1.1 on 2022-11-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('item', '0010_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='category.category'),
        ),
    ]
