# Generated by Django 4.1.1 on 2023-01-18 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='important_dates',
        ),
    ]
