# Generated by Django 4.1.1 on 2023-01-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('item_split', '0001_initial'), ('item_split', '0002_itemsplit_is_shared_with_item_user_and_more'), ('item_split', '0003_alter_itemsplit_shared_amount'), ('item_split', '0004_alter_itemsplit_shared_amount'), ('item_split', '0005_alter_itemsplit_shared_amount'), ('item_split', '0006_alter_itemsplit_item')]

    initial = True

    dependencies = [
        ('item', '0011_item_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_user_ids', models.CharField(max_length=100)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_user', to='item.item')),
                ('is_shared_with_item_user', models.BooleanField(default=False)),
                ('shared_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
        ),
    ]
