# Generated by Django 4.1.1 on 2023-01-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_split', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsplit',
            name='is_shared_with_item_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemsplit',
            name='shared_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
