# Generated by Django 4.1.1 on 2023-01-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_split', '0002_itemsplit_is_shared_with_item_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsplit',
            name='shared_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
