# Generated by Django 4.1.1 on 2023-01-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_split', '0003_alter_itemsplit_shared_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsplit',
            name='shared_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
