# Generated by Django 4.1.1 on 2023-01-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_split', '0004_alter_itemsplit_shared_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsplit',
            name='shared_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
