# Generated by Django 4.1.1 on 2023-02-15 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_remove_item_important_dates'),
        ('item_split', '0001_squashed_0006_alter_itemsplit_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsplit',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='item.item'),
        ),
        migrations.AlterField(
            model_name='itemsplit',
            name='shared_amount',
            field=models.CharField(max_length=100),
        ),
    ]
