# Generated by Django 4.1.1 on 2022-11-17 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import receipts.models


class Migration(migrations.Migration):

    replaces = [('receipts', '0001_initial'), ('receipts', '0002_receipts_merchant'), ('receipts', '0003_receipts_coupon_receipts_location_receipts_tax_and_more'), ('receipts', '0004_alter_receipts_merchant'), ('receipts', '0005_receipts_currency_receipts_important_dates'), ('receipts', '0006_alter_receipts_currency'), ('receipts', '0007_alter_receipts_location'), ('receipts', '0008_alter_receipts_coupon_alter_receipts_currency_and_more'), ('receipts', '0002_receipts_receipt_text'), ('receipts', '0007_merge_20221102_0238'), ('receipts', '0009_merge_20221104_2058'), ('receipts', '0010_alter_receipts_merchant_alter_receipts_scan_date_and_more'), ('receipts', '0010_alter_receipts_merchant_alter_receipts_receipt_image_and_more'), ('receipts', '0011_merge_20221112_1621'), ('receipts', '0012_alter_receipts_receipt_image'), ('receipts', '0013_remove_receipts_important_dates'), ('receipts', '0014_alter_receipts_receipt_image')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant', '0001_initial'),
        ('merchant', '0002_alter_merchant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('receipt_image', models.ImageField(default=1, upload_to=receipts.models.upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant', to='merchant.merchant')),
                ('coupon', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('tip', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('receipt_text', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
