# Generated by Django 4.1.1 on 2022-10-17 23:00

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(upload_to=receipts.models.upload_to),
        ),
    ]
