# Generated by Django 4.1.1 on 2022-10-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='receipt_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
