# Generated by Django 4.1.1 on 2022-10-12 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_alter_receipts_receipt_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipts",
            old_name="receipt_image",
            new_name="receipt_image_url",
        ),
        migrations.AlterField(
            model_name="receipts",
            name="scan_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 12, 0, 41, 53, 292205, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
