# Generated by Django 4.1.1 on 2022-10-10 04:52

import datetime
from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_alter_receipts_receipts"),
    ]

    operations = [
        migrations.RemoveField(model_name="receipts", name="receipts",),
        migrations.AddField(
            model_name="receipts",
            name="receipt_image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=receipts.models.upload_to
            ),
        ),
        migrations.AddField(
            model_name="receipts",
            name="scan_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
