# Generated by Django 4.1.1 on 2022-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipts_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='coupon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipts',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipts',
            name='tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipts',
            name='tip',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipts',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
