# Generated by Django 4.1.1 on 2022-10-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_alter_merchant_name'),
        ('receipts', '0003_receipts_coupon_receipts_location_receipts_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='merchant', to='merchant.merchant'),
        ),
    ]
