# Generated by Django 4.1.1 on 2022-10-11 08:36

import datetime
from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "receipts",
            "0003_remove_receipts_receipts_receipts_receipt_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipts",
            name="receipt_image_url",
            field=models.ImageField(
                default="receipt_images/default.jpg",
                upload_to=receipts.models.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="receipts",
            name="scan_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
