# Generated by Django 4.1.1 on 2022-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0004_alter_receipts_receipt_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipts", name="receipt_image_url", field=models.TextField(),
        ),
    ]
