# Generated by Django 4.1.1 on 2022-11-04 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_receipts_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='time_of_sale',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 14, 11, 51, 227696, tzinfo=datetime.timezone.utc)),
        ),
    ]
