# Generated by Django 4.1.1 on 2022-11-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipts_receipt_text'),
        ('receipts', '0006_alter_receipts_currency'),
    ]

    operations = [
    ]
