# Generated by Django 4.1.1 on 2022-11-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_receipts_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
