# Generated by Django 4.1.1 on 2022-11-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_merge_20221102_0238'),
        ('receipts', '0007_receipts_time_of_sale'),
    ]

    operations = [
    ]
