# Generated by Django 4.1.1 on 2022-11-04 00:48

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_receipts_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='important_dates',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=receipts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='tip',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
