# Generated by Django 4.1.1 on 2022-11-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_merge_20221102_0238'),
        ('receipts', '0008_alter_receipts_coupon_alter_receipts_currency_and_more'),
    ]

    operations = [
    ]
