# Generated by Django 4.1.1 on 2022-11-05 23:46

from django.db import migrations, models
import django.utils.timezone
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_merge_20221104_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(null=True, upload_to=receipts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='scan_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
