# Generated by Django 4.1.1 on 2022-10-12 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0010_alter_receipts_scan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipts",
            name="scan_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 12, 1, 3, 27, 166451, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
