# Generated by Django 4.1.1 on 2022-11-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_alter_receipts_merchant_alter_receipts_receipt_image_and_more'),
        ('receipts', '0010_alter_receipts_merchant_alter_receipts_scan_date_and_more'),
    ]

    operations = [
    ]
