# Generated by Django 4.1.1 on 2022-11-12 21:21

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_merge_20221112_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=receipts.models.upload_to),
        ),
    ]
