# Generated by Django 4.1.1 on 2022-11-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_alter_receipts_receipt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='important_dates',
        ),
    ]
