# Generated by Django 4.1.1 on 2022-11-17 06:04

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_remove_receipts_important_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(default=1, upload_to=receipts.models.upload_to),
            preserve_default=False,
        ),
    ]
