# Generated by Django 4.1.1 on 2022-11-17 20:55

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_squashed_0014_alter_receipts_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(upload_to=receipts.models.upload_to),
        ),
    ]
