# Generated by Django 4.1.1 on 2022-10-12 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0014_alter_receipts_scan_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipts",
            old_name="receipt_image_url",
            new_name="receipt_image",
        ),
        migrations.AlterField(
            model_name="receipts",
            name="scan_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 12, 1, 34, 22, 627782, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
