# Generated by Django 4.1.1 on 2023-01-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_alter_receipts_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
