# Generated by Django 4.1.1 on 2023-03-11 16:36

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0016_alter_receipts_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=receipts.models.upload_to),
        ),
    ]
