# Generated by Django 4.1.1 on 2023-04-01 16:19

from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0017_alter_receipts_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receipt_image',
            field=models.ImageField(default=2, upload_to=receipts.models.upload_to),
            preserve_default=False,
        ),
    ]
