# Generated by Django 4.1.1 on 2022-10-12 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0017_alter_receipts_scan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipts",
            name="scan_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 10, 12, 4, 15, 55, 131156, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
