# Generated by Django 4.1.1 on 2022-10-12 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0018_alter_receipts_scan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipts",
            name="scan_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 12, 4, 18, 0, 651658)
            ),
        ),
    ]
