# Generated by Django 4.1.1 on 2022-10-13 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0020_alter_receipts_scan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipts",
            name="scan_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
