# Generated by Django 4.1.1 on 2022-11-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=30)),
                ('category_toggle_star', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.category')),
                ('sub_category_name', models.CharField(blank=True, default='', max_length=30)),
                ('sub_category_toggle_star', models.BooleanField(default=False)),
            ],
            bases=('category.category',),
        ),
    ]
