# Generated by Django 4.1.1 on 2022-11-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
    ]
