# Generated by Django 4.1.1 on 2023-01-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
