# Generated by Django 4.1.1 on 2022-11-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_sub_category_id'),
        ('category', '0003_category_user_subcategory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category_id',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
