# Generated by Django 4.1.1 on 2022-11-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_parent_category_id_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category_id',
            field=models.IntegerField(blank=True),
        ),
    ]
