# Generated by Django 4.1.1 on 2023-01-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("receipts", "0016_alter_receipts_receipt_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_user_ids", models.CharField(max_length=100)),
                ("is_shared_with_receipt_owner", models.BooleanField(default=False)),
                (
                    "shared_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="receipt_user",
                        to="receipts.receipts",
                    ),
                ),
            ],
        ),
    ]
