# Generated by Django 4.1.1 on 2023-02-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_split', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsplit',
            name='shared_amount',
            field=models.CharField(max_length=100),
        ),
    ]
